### ISSUE TITLE
localhostでの起動確認後の動作方法が記載されておらず動作方法が不明です。

### ISSUE THREAD

**Issue by UniMulRock** [kuboyoichiro/kuboyoichiro.github.io#1]
【現状】
localhostでの起動確認まで完了。
【不明点】
ログイン周りはロジック的にありそうなのですが、起動直後の画面にその辺は出てこない。
どこを見て問題出題するのか。
出題/正解表示のタイミングは進行に合わせて制御可能なのか。
当日実施まで結果が分からないような予想系の問題も出題可能なのか。

**Comment by kuboyoichiro** [comment]
## 前提
- フロントだけでは動作が完結しない（APIが必要）ので、完全な動作確認は出来ない見込み

## 構成
このリポジトリには大きく分けて3つの領域が存在します。
- ユーザーがモバイル端末でアクセスする画面
- スクリーンに移す画面
- 問題の出題等をコントロールする管理画面

> ログイン周りはロジック的にありそうなのですが、起動直後の画面にその辺は出てこない。

/login まわりにあります。トップページからロゴをタップするとログインページに飛ぶはず。

> どこを見て問題出題するのか。

管理画面で問題一覧を表示し、次に出題する問題を制御していました。ただし、正解の表示はスクリーン側で制御していました。

> 出題/正解表示のタイミングは進行に合わせて制御可能なのか。

これをマストで実現しないといけないので、スクリーン側で制御を入れていました。
https://github.com/kuboyoichiro/kuboyoichiro.github.io/blob/master/src/components/Screen.vue

にて、キー押下で表示を制御していました。

> 当日実施まで結果が分からないような予想系の問題も出題可能なのか。

可能ではある、という答えになります。
ただし、問題と選択肢・正解はサーバー管理だったので、進行に併せてマスタの値を書き換えるのはあまりに怖いのでオススメはしません。

**Comment by kuboyoichiro** [comment]
今見ると完全に気が狂ってる構成/実装っすね… 😇

**Comment by UniMulRock** [comment]
本番でAPIが必要なのは分かりました。その他の件も理解しました。
ありがとうございます。
確認なのですが、localhostで実行する場合もサーバー側のAPI周りが必要という認識で合っていますでしょうか。

**Comment by kuboyoichiro** [comment]
@UniMulRock
https://github.com/kuboyoichiro/kuboyoichiro.github.io/blob/master/src/assets/url.js 
そうですね、必要になります。モックサーバーはおろかdev環境を考える余裕もなかったので本番環境に常に接続して開発してた覚えがあります。せめてレスポンス一覧とかが見つかれば良いのですが…

**Comment by UniMulRock** [comment]
@kuboyoichiro 
なるほど。承知致しました。
> せめてレスポンス一覧とかが見つかれば良いのですが…
あ、それ欲しいですね…
自前でサーバー側を組むにしてもAPI一覧がないと厳しそうです。

**Comment by kuboyoichiro** [comment]
レスポンス一覧はサーバーの人に祈るしかなさそう 🙏

**Comment by UniMulRock** [comment]
承知致しました。
一旦、このissueはCloseしておきます。
